### ISSUE TITLE
Javascript function words disapears

### ISSUE THREAD

**Issue by gmiles33** [danyaPostfactum/ckeditor-autocorrect-plugin#14]
Some words will disappear when entered. Need to match the case. 

Some examples

All browsers 'toString'

FireFox 'watch'

**Comment by danyaPostfactum** [comment]
Good catch. Thanks for report :+1: 
Fixed https://github.com/danyaPostfactum/ckeditor-autocorrect-plugin/commit/7c8777bd1090276cecddf6bf051696cf16fb6cad
