### ISSUE TITLE
Autocorrect custom text

### ISSUE THREAD

**Issue by ermiri** [danyaPostfactum/ckeditor-autocorrect-plugin#16]
I would like to add some custom autocorrect text.
For example 12345 replace to: That is a beautiful a day.
How can i do that?
I tried to edit:
CKEDITOR.config.autocorrect_replacementTable = {"-->": "→", "-+": "∓", "->": "→", "...": "…", "(c)": "©", "(e)": "€", "(r)": "®", "(tm)": "™", "(o)": "˚", "+-": "±", "<-": "←", "<--": "←", "<-->": "↔", "<->": "↔", "<<": "«", ">>": "»", "~=": "≈", "1/2": "½", "1/4": "¼", "3/4": "¾", "12345 ": "That is a beautiful a day"};
but no results.

**Comment by jasonluttrell** [comment]
I know this is really old, but if anyone else has trouble with this more recently, try using the CKEditor config module:

https://www.drupal.org/project/ckeditor_config
