### ISSUE TITLE
Add button in personal menu

### ISSUE THREAD

**Issue by liladude** [danyaPostfactum/ckeditor-autocorrect-plugin#26]
Hi, thank you for this plugin!
I am trying to use it and I manually added it to my ckfinder and enabled it. It works, which is lovely!
Now I'm playing with the options but I seem unable to find the name of the button in order to call it and add it in my menu. I tried "autocorrect", "Autocorrect", "autocorrectButton"... Can someone point me to the correct definition?
I have read all the related issues, but I cannot find the info for manual adding the button.

**Comment by liladude** [comment]
Sorry, finally found the correct label! it is 'AutoCorrect', it would be nice to have this mentioned in the readme after the info about enabling the plugin!

**Comment by danyaPostfactum** [comment]
Thanks. I have added this info.
